In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('./Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features, with StandardScaler around the mean value of the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('./label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('./onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('./scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

In [13]:
# Ensure TensorFlow uses the GPU
physical_devices = tf.config.list_physical_devices('GPU')
if physical_devices:
    try:
        tf.config.experimental.set_memory_growth(physical_devices[0], True)
        print("GPU is available and configured.")
    except RuntimeError as e:
        print(e)

In [14]:
# Build the model
model = Sequential()
model.add(Input(shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))  # Output layer for regression

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [16]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [17]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 102326.8203 - mae: 102326.8203 - val_loss: 98569.1953 - val_mae: 98569.1953
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 99725.2109 - mae: 99725.2109 - val_loss: 97363.6250 - val_mae: 97363.6250
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 98336.2969 - mae: 98336.2969 - val_loss: 94224.2266 - val_mae: 94224.2266
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 94997.6484 - mae: 94997.6484 - val_loss: 88860.5469 - val_mae: 88860.5469
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 89751.7578 - mae: 89751.7578 - val_loss: 81674.0938 - val_mae: 81674.0938
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 80344.4688 - mae: 80344.4688 - val_loss: 73611.9766 - val_mae: 73611.9766
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 73540.7969 - mae: 73540.7969 - val_loss: 65898.7578 - val_mae: 65898.7578
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 64409.6484 - mae: 64409.6484 - val_loss: 59508.8945 - val_mae: 59508.8945
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 58322.8867 - mae: 58322.8867 - val_loss: 55108.6406 - val_mae: 55108.6406
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 54992.9922 - mae: 54992.9922 - val_loss: 52605.0273 - val_mae: 52605.0273
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 52152.3633 - mae: 52152.3633 - val_loss: 51482.1133 - val_mae: 51482.1133
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51486.9766 - mae: 51486.9766 - val_loss: 51080.5625 - val_mae: 51080.5625
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50639.4023 - mae: 50639.4023 - val_loss: 50919.0664 - val_mae: 50919.0664
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50558.5898 - mae: 50558.5898 - val_loss: 50843.5117 - val_mae: 50843.5117
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49883.5742 - mae: 49883.5742 - val_loss: 50783.8516 - val_mae: 50783.8516
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50048.8242 - mae: 50048.8242 - val_loss: 50739.8086 - val_mae: 50739.8086
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50222.0859 - mae: 50222.0859 - val_loss: 50698.4141 - val_mae: 50698.4141
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49687.1680 - mae: 49687.1680 - val_loss: 50659.6328 - val_mae: 50659.6328
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50582.3047 - mae: 50582.3047 - val_loss: 50625.2969 - val_mae: 50625.2969
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49734.0273 - mae: 49734.0273 - val_loss: 50594.5430 - val_mae: 50594.5430
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49923.2188 - mae: 49923.2188 - val_loss: 50560.8789 - val_mae: 50560.8789
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49747.8867 - mae: 49747.8867 - val_loss: 50535.7305 - val_mae: 50535.7305
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50284.9570 - mae: 50284.9570 - val_loss: 50511.5195 - val_mae: 50511.5195
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49796.2852 - mae: 49796.2852 - val_loss: 50496.1992 - val_mae: 50496.1992
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50238.7266 - mae: 50238.7266 - val_loss: 50475.0312 - val_mae: 50475.0312
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49903.0664 - mae: 49903.0664 - val_loss: 50461.1797 - val_mae: 50461.1797
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49319.7188 - mae: 49319.7188 - val_loss: 50442.7461 - val_mae: 50442.7461
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50168.6523 - mae: 50168.6523 - val_loss: 50425.5938 - val_mae: 50425.5938
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49763.8945 - mae: 49763.8945 - val_loss: 50419.8398 - val_mae: 50419.8398
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50187.4648 - mae: 50187.4648 - val_loss: 50410.8633 - val_mae: 50410.8633
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49900.0078 - mae: 49900.0078 - val_loss: 50398.1055 - val_mae: 50398.1055
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49288.5781 - mae: 49288.5781 - val_loss: 50395.4336 - val_mae: 50395.4336
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49442.6641 - mae: 49442.6641 - val_loss: 50372.1562 - val_mae: 50372.1562
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49467.3320 - mae: 49467.3320 - val_loss: 50374.6406 - val_mae: 50374.6406
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49524.2969 - mae: 49524.2969 - val_loss: 50366.7617 - val_mae: 50366.7617
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49006.5586 - mae: 49006.5586 - val_loss: 50362.6602 - val_mae: 50362.6602
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49691.2695 - mae: 49691.2695 - val_loss: 50352.0742 - val_mae: 50352.0742
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49728.4297 - mae: 49728.4297 - val_loss: 50346.0977 - val_mae: 50346.0977
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49900.1328 - mae: 49900.1328 - val_loss: 50343.8711 - val_mae: 50343.8711
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49945.0391 - mae: 49945.0391 - val_loss: 50339.2695 - val_mae: 50339.2695
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49001.9258 - mae: 49001.9258 - val_loss: 50344.1484 - val_mae: 50344.1484
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49823.6328 - mae: 49823.6328 - val_loss: 50335.0156 - val_mae: 50335.0156
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49716.9336 - mae: 49716.9336 - val_loss: 50327.4102 - val_mae: 50327.4102
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49960.4219 - mae: 49960.4219 - val_loss: 50327.5234 - val_mae: 50327.5234
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49423.4453 - mae: 49423.4453 - val_loss: 50318.0508 - val_mae: 50318.0508
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49575.6719 - mae: 49575.6719 - val_loss: 50319.6016 - val_mae: 50319.6016
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49338.9531 - mae: 49338.9531 - val_loss: 50323.1016 - val_mae: 50323.1016
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49434.0586 - mae: 49434.0586 - val_loss: 50319.0039 - val_mae: 50319.0039
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49606.8164 - mae: 49606.8164 - val_loss: 50310.1680 - val_mae: 50310.1680
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49184.3789 - mae: 49184.3789 - val_loss: 50312.1133 - val_mae: 50312.1133
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49493.9180 - mae: 49493.9180 - val_loss: 50316.0273 - val_mae: 50316.0273
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49505.1836 - mae: 49505.1836 - val_loss: 50313.6914 - val_mae: 50313.6914
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49497.5664 - mae: 49497.5664 - val_loss: 50312.4922 - val_mae: 50312.4922
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49622.7422 - mae: 49622.7422 - val_loss: 50313.0078 - val_mae: 50313.0078
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49644.9375 - mae: 49644.9375 - val_loss: 50306.5586 - val_mae: 50306.5586
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49321.8828 - mae: 49321.8828 - val_loss: 50313.4883 - val_mae: 50313.4883
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49109.7539 - mae: 49109.7539 - val_loss: 50303.3008 - val_mae: 50303.3008
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49004.0430 - mae: 49004.0430 - val_loss: 50299.8477 - val_mae: 50299.8477
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50193.6172 - mae: 50193.6172 - val_loss: 50305.6953 - val_mae: 50305.6953
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49601.8828 - mae: 49601.8828 - val_loss: 50319.7812 - val_mae: 50319.7812
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49313.8984 - mae: 49313.8984 - val_loss: 50316.0664 - val_mae: 50316.0664
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49609.3203 - mae: 49609.3203 - val_loss: 50310.1680 - val_mae: 50310.1680
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49201.8203 - mae: 49201.8203 - val_loss: 50326.8398 - val_mae: 50326.8398
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49421.0430 - mae: 49421.0430 - val_loss: 50334.4453 - val_mae: 50334.4453
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50002.5508 - mae: 50002.5508 - val_loss: 50320.4453 - val_mae: 50320.4453
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48513.6055 - mae: 48513.6055 - val_loss: 50325.8867 - val_mae: 50325.8867
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48985.7930 - mae: 48985.7930 - val_loss: 50324.2930 - val_mae: 50324.2930
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 49746.7617 - mae: 49746.7617 - val_loss: 50333.5391 - val_mae: 50333.5391

In [18]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51091.3281 - mae: 51091.3281
Test MAE : 50299.84765625

In [19]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
%load_ext tensorboard

In [ ]:
%tensorboard --logdir regressionlogs/fit